language: java
sudo: false
jdk: oraclejdk8
install: mvn ${SPARK} ${SCALA} -Dmaven.javadoc.skip=true -DskipTests=true -B -V -Dgpg.skip=true install
script: mvn ${SPARK} ${SCALA} -Dmaven.javadoc.skip=true -q -B -Dgpg.skip=true verify
env:
  global:
    - MAVEN_OPTS=-Xmx2g
matrix:
  include:
    # Covers Spark 1.3.x
    - env: SPARK=-Dspark.version=1.3.1
    # Covers Spark 1.4.x
    - env: SPARK=-Dspark.version=1.4.1
    # Covers Spark 1.5.x
    - env: SPARK=-Dspark.version=1.5.2
    # Covers Scala 2.11, Spark 1.6.x
    - env: SCALA=-Pscala-2.11 SPARK=-Dspark.version=1.6.0
cache:
  directories:
    - $HOME/.m2
